<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
  @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<div class="entry-edit">
	<div class="entry-edit-head"><h4 class="icon-head head-customer-view"><?php echo Mage::helper('rma')->__('Request Information') ?></h4></div>
	<fieldset>
		<table cellspacing="2" class="box-left">
			<tr>
				<td><strong><?php echo $this->__('Request Date:') ?></strong></td>
				<td><?php echo Mage::helper('rma/request')->getDateFormate($data['created_at']);?></td>
			</tr>
			<tr>
				<td><strong><?php echo $this->__('Request Type:') ?></strong></td>
				<td><?php echo $data['type'];?></td>
			</tr>
			<tr>
				<td><strong><?php echo $this->__('Reason type:') ?></strong></td>
				<td><?php echo $data['reason'];?></td>
			</tr>
			<tr>
				<td><strong><?php echo $this->__('Reason Description:') ?></strong></td>
				<td><?php echo $data['descriptions'];?></td>
			</tr>
		</table>
	</fieldset>
</div>

<div class="clear"></div>
<div class="box-left">
	<div class="entry-edit">
		<div class="entry-edit-head"><h4 class="icon-head head-customer-view"><?php echo Mage::helper('rma')->__('Product Details ') ?></h4></div>
		<fieldset>
			<table cellspacing="2">
				<tr>
					<td><strong><?php echo $this->__('Product Name:') ?></strong></td>
					<td><?php echo $data['pName']; ?></td>
				</tr>
				
				<tr>
					<td><strong><?php echo $this->__('Sku Number:') ?></strong></td>
					<td><?php echo $data['sku_number'];?></td>
				</tr>
				<tr>
					<td><strong><?php echo $this->__('Serial Number:') ?></strong></td>
					<td><?php echo $data['serial_number'];?></td>
				</tr>
				<tr>
					<td><strong><?php echo $this->__('date of shipment:') ?></strong></td>
					<td> <?php echo date("D, j M, Y", strtotime($data['date_of_shipment']));?> </td>
				</tr>
				<tr>
					<td><strong><?php echo $this->__('Sold within 1 year:') ?></strong></td>
					<td> 
						<?php 
							$image=Mage::helper('rma/request')->checkDateWithinYear($data['date_of_shipment']);
						?>
						<img src="<?php echo $this->getSkinUrl($image);?>" alt="">
					</td>
				</tr>
				
				<tr>
					<td><strong><?php echo $this->__('Warrenty period:') ?></strong></td>
					<td>
						<?php 
							$image=Mage::helper('rma/request')->checkWarranty_period($data['date_of_shipment'],$data['warranty_period']);
						?>
						<img src="<?php echo $this->getSkinUrl($image);?>" alt="">
					</td>
				</tr>
			</table>
		</fieldset>
	</div>
</div>

<div class="box-right">
	<div class="entry-edit">
		<div class="entry-edit-head"><h4 class="icon-head head-customer-view"><?php echo Mage::helper('rma')->__('Status') ?></h4></div>
		<fieldset>
			<table cellspacing="2" class="box-left">
				<tr>
					<td><strong><?php echo $this->__('Rma Status:') ?></strong></td>
					<td><?php echo Mage::helper('rma/request')->getRmaStatus($data['status']);?></td>
				</tr>
				
				
			</table>
		</fieldset>
	</div>
</div>
<div class="clear"></div>
<div class="box-left">
	<div class="entry-edit">
	<?php
		if($data['status'] == 0){
			$link= Mage::helper('adminhtml')->getUrl('adminhtml/request/status/') ."id/".$data['item_id']."/cid/".$data['customer_id']."/status/";
			echo $statusLink=Mage::helper('rma/request')->getStatusLink($data['status'],$link);
		}
	?>
	</div>
</div>
