/*
jQuery plugin to add functionality to your forms to add multiple records on single click on the fly using client side javascript
author: Vipul Limbachiya
http://vipulilmbachiya.com
*/

/* 
 * This program is free software. It comes without any warranty, to the extent permitted by applicable law. 
 * You can redistribute it and/or modify it without any terms.
 * Save developers, use Firefox http://firefox.com
*/

eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('(b($){$.Y.W=b(1){1=$.X({z:\'U 11\',6:\'14\',y:E,B:\'i\',9:\'13\',T:E,R:\'12 M 15 M 16 Z i V 18(s)?\',D:d,I:d,l:d,F:d},1);g 8.O(b(){e 2=$(8);$(2).3("q","0");$(2).3("S","w");$(2).3("C","0");$(2).3("k",1.6+L.Q());$(2).4("."+1.6).i();$(2).4("."+1.9).i();$(2).m(" <a n=\'#\' o=\'"+1.6+"\'>"+1.z+"</a>");$(2).4("."+1.6).p(b(){g v($(8))});e P=$(2).N();b v(c){e h=H($(2).3("q"),10);e r=H($(2).3("C"),10);5(1.l===d||h<1.l){e 7=P.N();$(7).4("*[t!=\'\'][u!=\'\']").O(b(){5($(8).3("t")){e K=$(8).3("t");e J="";5($(8).3("u")){J=$(8).3("u")}$(8).3("t",K+"1g"+r);$(8).3("u",J+"$"+r)}});h++;r++;$(2).3("q",h);$(2).3("C",r);$(7).1f("k");5(1.y&&$(2).3("k")!=$(c).f().3("k")){5($(c).f().4("."+1.9).x===0){$(c).f().m(" <a n=\'#\' o=\'"+1.9+"\'>"+1.B+"</a>")}$(c).f().4("."+1.9).p(b(){g A($(8))})}$(7).3("k",1.6+L.Q());$(c).f().1e(7);$(c).f().4("."+1.6).i();$(7).4("."+1.6).i();$(7).4("."+1.9).i();5(1.y){5($(7).4("."+1.9).x===0){$(7).m(" <a n=\'#\' o=\'"+1.9+"\'>"+1.B+"</a>")}$(7).4("."+1.9).p(b(){g A($(8))})}$(2).3("S","w");$(7).m(" <a n=\'#\' o=\'"+1.6+"\'>"+1.z+"</a>");7.4("."+1.6).p(b(){g v($(8))});5(1.D!==d){1.D($(7),2)}}5(1.l!==d&&h>=1.l){7.4("."+1.6).1c();5(1.F!==d){1.F($(7),2)}}g w}b A(c){e G=E;5(1.T){G=1d(1.R)}5(G){e j=$(c).f().17();e h=H($(2).3("q"),10);h--;$(2).3("q",h);5($(c).f().4("."+1.6).x>0){5(1.y&&$(2).3("k")!=$(j).3("k")){5($(j).4("."+1.9).x===0){$(j).m(" <a n=\'#\' o=\'"+1.9+"\'>"+1.B+"</a>")}$(j).4("."+1.9).p(b(){g A($(8))})}$(j).m(" <a n=\'#\' o=\'"+1.6+"\'>"+1.z+"</a>");j.4("."+1.6).p(b(){g v($(8))})}5(1.l!==d&&h<1.l){$(2).1a().4("."+1.6).1b()}$(c).f().i();5(1.I!==d){1.I($(j),2)}}g w}})}})(19);',62,79,'|options|self|attr|find|if|linkClass|newElem|this|removeLinkClass||function|elem|null|var|parent|return|totalCount|remove|prevParent|uniqueId|maxItemsAllowedToAdd|append|href|class|click|TotalFieldsAdded|fieldCount||id|name|handleAdd|false|length|enableRemove|linkText|handleRemove|removeLinkText|FieldCount|addEventCallback|true|maxItemReachedCallback|cnt|parseInt|removeEventCallback|strname|strid|Math|you|clone|each|myClone|random|confirmationMsgOnRemove|maxCountReached|confirmOnRemove|add|selected|EnableMultiField|extend|fn|to||more|Are|removeFields|addMoreFields|sure|wish|prev|field|jQuery|siblings|show|hide|confirm|after|removeAttr|_'.split('|'),0,{}))
