<?php 
/**
 * Request_Rma extension
 * Rma request template
 *
 * @category	Request
 * @package		Request_Rma
 * @author      Tosif Qureshi
 */
?>
<?php 
/* Get rma type data */
$rma_type = $this->getRmaType();
/* Get rma order products data*/
$rma_products = Mage::helper('rma/request')->getProductItemData($this->getOrderId());
/* Get order is expired or not */
$is_order_expired = $this->getOrderDays($this->getOrderId());
?>
<div class="block block-subscribe">
	<div class="block-title">
        <strong><span><?php echo $this->__('RMA');?></span></strong>
    </div>
	<!-- Rma form to select report type-->
	<form id="rma_form" name="rma_form" action="<?php echo $this->getUrl('rma/request/');?>rmaTypeForm" method="post">
		 <div class="block-content">
			<!-- Div start of sku number-->
			<div class="clear"></div>
			<div class="input-box form-list">
				<label class="required"><em>*</em>
				<select name="sku_number" id="sku_number" class="required-entry">
					<option value=""><?php echo $this->__('Select your SKU number');?></option>
					<?php
					 for($i=0;$i<count($rma_products);$i++) : ?>
						<option value="<?php echo $rma_products[$i]['product_sku'];?>"><?php echo $rma_products[$i]['product_sku'];?></option>
					 <?php endfor; ?>
				</select>
				</label>
			</div>
			<div class="clear"></div>
			<!-- Div end of sku number-->
				
			<!-- Div start of rma form type -->
			<?php 
			foreach($rma_type as $rma_type) :
				if($is_order_expired || $rma_type->getId()==1) :
					//Set default check value
					$is_checked = '';
					if ($rma_type->getId()==1) :
						$is_checked = 'checked';
					endif;?>
					<div class="form-subscribe-header mt3">
						<input type="radio" name="rma_type" id="rma_type_<?php echo $rma_type->getId();?>" value="<?php echo $rma_type->getId();?>" <?php echo $is_checked;?>>
						<label for="type"><?php echo $rma_type->getType();?>
							<span></span>
						</label>
					</div>
				<?php 
				endif; 
			endforeach;?>
			<!-- Div end of rma form type -->
			
			<!-- Set here hidden input field of order id-->
			<input type="hidden" name="order_id" value="<?php echo $this->getOrderId();?>">
			<!-- Set here hidden input field of order id-->
			<input type="hidden" name="rma_id" value="<?php echo $this->getRmaId();?>">
			<div class="clear"></div>
			<!-- Div start here of submit button -->
			<div class="actions">
				<button type="submit" class="button">
					<p class="required"><?php echo $this->__('* Required Fields') ?></p>
					<span><?php echo $this->__('Submit');?></span>
				</button>	
			</div>
			<!-- Div end here of submit button -->
		</div>
	</form>
</div>
<!-- Div start here for back url -->
<div class="buttons-set">
	<p class="back-link"><a href="<?php echo $this->getOrderBackUrl() ?>"><small>&laquo; </small><?php echo $this->getBackTitle() ?></a></p>
</div>

<script type="text/javascript">
	
    //<![CDATA[
        var rmaFormDetail = new VarienForm('rma_form');
    //]]>
    
    /**
    * Check the sku product is exist or not
    */
    jQuery(document).ready(function() {
		 jQuery('select[name="sku_number"]').change(function() {
			 /* get selected sku number value */
			 var sku = jQuery('#sku_number').val();
			 if(sku!='') {
				jQuery.post(	
					'<?php echo $this->getUrl('rma/request/checkItemExist') ?>',
					jQuery("#rma_form").serialize(),
					function(data){
						var result = eval("(" + data + ")");
						if(result.isExist==true) {
							alert('You have already RMA for this product');
							jQuery("#sku_number option[value='']").attr("selected", "selected");
						}
				});
			}
		});
	});
</script>


