<?php 
/**
 * Request_Rma extension
 * Rma view template
 *
 * @category	Request
 * @package		Request_Rma
 * @author      Tosif Qureshi
 */
?>
<?php
/* Get all rma records */
$_rma = $this->getCollection();
?>
  <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="block block-subscribe">
	<div class="block-title lh18">
		<!-- Set page title here -->
		<div class="fl width130px"><strong><span><?php echo $this->__('Rma Listing');?></span></strong></div>
		<!-- Set tab to report rma -->
		<div class="tar">
			&nbsp;
			<!--<a href="<?php //echo $this->getUrl('rma/request/rmaform');?>">
				<?php //echo $this->__('Request Rma');?>
			</a>-->
		</div>
    </div>
  
    <?php echo $this->getPagerHtml(); ?>
    <div class="block-content">
    <?php if ($_rma->getSize() > 0) :?>
		<!-- Rma listing start here -->
			<table class="rmaListTable">
				<thead>
					<tr class="headings rmaListTr">
						<th class="rmaListTh <?php echo $this->getSortIcon('id');?>">
							<a href="<?php echo $this->getRmaSortingUrl('id');?>"><?php echo $this->__('RMA Id');?></a>
						</th>
						<th class="rmaListTh <?php echo $this->getSortIcon('order_id');?>">
							<a href="<?php echo $this->getRmaSortingUrl('order_id');?>"><?php echo $this->__('Order Id');?></a>
						</th>
						<th class="rmaListTh <?php echo $this->getSortIcon('rma_item_count');?>">
							<a href="<?php echo $this->getRmaSortingUrl('rma_item_count');?>"><?php echo $this->__('Item Count');?></a>
						</th>
						<th class="rmaListTh <?php echo $this->getSortIcon('created');?>">
							<a href="<?php echo $this->getRmaSortingUrl('created');?>"><?php echo $this->__('Date');?></a></th>
						<th class="rmaListTh"></th>
					</tr>
				</thead>
				<?php foreach($_rma as $_rma) :?>
					<tr class="lh25">
						<td class="rmaListCol">
							<?php echo $_rma->getId(); ?>
						</td>
						<td class="rmaListCol">
							<?php echo $this->getRealOrderId($_rma->getId()); ?>
						</td>
						<td class="rmaListCol">
							<?php echo $_rma->getRma_item_count(); ?>
						</td>
						<td class="rmaListCol">
							<?php echo $this->getCreatedDate($_rma->getCreated()); ?>
						</td>
						<td class="rmaListCol">
							<a href="<?php echo $this->getRmaViewUrl($_rma->getId());?>" class="viewDetail"><?php echo $this->__('View Details');?></a>
							<?php if($_rma['is_submitted']==0) :?>
								| <a href="<?php echo $this->getRmaEditUrl($_rma->getId());?>" class="textDecoNone"><?php echo $this->__('Edit Details');?></a>
							<?php endif;?>
						</td>
					</tr>
				<?php endforeach;?>
			</table>
		<?php echo $this->getPagerHtml(); ?>
		<!-- Rma listing end here -->
	<?php else : ?>
		<?php echo Mage::helper('rma')->__('There are no RMA at this moment');?>
	<?php endif;?> 
	</div>
</div>
