<?php 
/**
 * Request_Rma extension
 * Rma view template
 *
 * @category	Request
 * @package		Request_Rma
 * @author      Tosif Qureshi
 */

/* Get rma details of current rma */
$rma = $this->getRmaItemData();
/* Get customer address details */
$custAddress = $this->getCustomerAddress();
/* Initialize default count as 1 */
$i = 1;

if (count($rma) > 0) :
	foreach($rma as $data) :
	
	/* Get return amount of product */
	$_order = Mage::getModel('sales/order')->load($data['order_id']);
    $total_amount = Mage::helper('rma/request')->getItemAmount($_order,$data['product_id'],$data['quantity']);
    /* Get credit memos records */
	$_credit_memos = Mage::helper('rma/request')->getCreditMemo($data['order_id'],$data['product_id']);
	?>
		<div class="block">
			<div class="block-title lh18">
				<!-- Set page title here -->
				<div class="fl width130px">
					<strong>
						<span><?php echo $this->getRmaHeadTitleId($data['item_id']);?></span>
					</strong>
				</div>
				<!-- Set tab to report rma -->
				<div class="tar">&nbsp;</div>
			</div>
     
			<div class="block-content">
				<div>
					<div class="journTxtDiv"><?php echo $this->__('Journal');?></div>
					<!-- Left side rma detail div start here -->
					<div class="detailTbl detailLeft">
						<div class="rmaDetailHead">
							<span class="ml10"><?php echo $this->__('RMA Details');?></span>
						</div>
						<fieldset>
							<table cellspacing="2">
								<!-- RMA number display here -->
								<tr>
									<td class="detailLblTd"><strong><?php echo $this->__('RMA Number:');?></strong></td>
									<td><?php echo $this->getRmaId($data['rma_id']);?></td>
								</tr>
								<!-- Date display here -->
								<tr>
									<td><strong><?php echo $this->__('Date:');?></strong></td>
									<td><?php echo $this->getItemDate($data['created_at']);?></td>
								</tr>
								<!-- Order number display here -->
								<tr>
									<td><strong><?php echo $this->__('Order Number:');?></strong></td>
									<td><?php echo Mage::helper('rma/request')->getRealOrderId($data['rma_id']);?></td>
								</tr>
								<!-- Invoice number display here -->
								<tr>
									<td><strong><?php echo $this->__('Invoice Number:');?></strong></td>
									<td><?php echo !empty($data['invoice_number'])?$data['invoice_number']:'NA';?></td>
								</tr>
								<!-- Customer name display here -->
								<tr>
									<td><strong><?php echo $this->__('Name:');?></strong></td>
									<td><?php echo $this->getUserName();?></td>
								</tr>
								<!-- Customer address display here -->
								<tr>
									<td><strong><?php echo $this->__('Address:');?></strong></td>
									<td><?php echo $this->getStreetAddress($custAddress->getStreet());?></td>
								</tr>
								<!-- Customer zip display here -->
								<tr>
									<td><strong><?php echo $this->__('Zip:');?></strong></td>
									<td><?php echo $custAddress->getPostcode();?></td>
								</tr>
								<!-- Customer city display here -->
								<tr>
									<td><strong><?php echo $this->__('City:');?></strong></td>
									<td><?php echo $custAddress->getCity();?></td>
								</tr>
								<!-- Customer country display here -->
								<tr>
									<td><strong><?php echo $this->__('Country:');?></strong></td>
									<td><?php echo $this->getCountryName($custAddress->getCountry_id());?></td>
								</tr>
								<!-- Customer phone number display here -->
								<tr>
									<td><strong><?php echo $this->__('Phone:');?></strong></td>
									<td><?php echo $custAddress->getTelephone();?></td>
								</tr>
								<!-- Customer email display here -->
								 <tr>
									<td><strong><?php echo $this->__('Email:');?></strong></td>
									<td><?php echo $this->getEmail();?></td>
								</tr>
								<!-- RMA item return type display here -->
								 <tr>
									<td><strong><?php echo $this->__('What do you want:');?></strong></td>
									<td><?php echo $this->getRmaType($data['type_id']);?></td>
								</tr>
								<!-- Change shipping address link display here -->
								<tr class="paddingTr">
									<td><strong></strong></td>
									<td>
										<a href="<?php echo $this->getShippingUrl($data['order_id'],$data['rma_id']);?>"><?php echo $this->__('Change shipping address');?></a>
									</td>
								</tr>
								<!-- Reason type display here -->
								<tr>
									<td><strong><?php echo $this->__('Reason:');?></strong></td>
									<td><?php echo $this->getRmaReason($data['reason_id']);?></td>
								</tr>
								<!-- product image display here -->
								<tr>
									<td><strong><?php echo $this->__('Photo:');?></strong></td>
									<td>
										<?php 
										/* Get base path of product image */
										$img_base_url = Mage::helper('rma/request')->getBaseImgPath($data['product_id']);
										if(file_exists($img_base_url)) : ?>
											<img src="<?php echo Mage::helper('rma/request')->getProductImg($data['product_id']);?>">
										<?php 
										else :
											echo "No Photo";
										endif;
										?>
									</td>
								</tr>
								<!-- Bottom saperator line -->
								<tr>
									<td colspan=2 class="rmaDetailSap"></td>
								</tr>
							
								<!-- Reason comments display here -->
								<tr class="paddingTr">
									<td><strong><?php echo $this->__('Comments:');?></strong></td>
									<td>
										<ul class="commentUl">
											<?php 
											foreach($this->getItemReasons($data['item_id']) as $reasonData):?>
											<li>
												<?php echo $reasonData->getDescriptions();?>
											</li>
											<?php endforeach;?>
										</ul>
									</td>
								</tr>
								
								<!-- Bottom saperator line -->
								<tr>
									<td colspan=2 class="rmaDetailSap"></td>
								</tr>
								<!-- Credit memos display here -->
								<tr class="paddingTr">
									<td><strong><?php echo $this->__('Credit memos:');?></strong></td>
									<td>
										<?php
										if(is_array($_credit_memos) && count($_credit_memos)>0) :
											for($i=0;$i<count($_credit_memos);$i++) : ?>
												<a href="<?php echo $this->getCreditMemoUrl($data['order_id']); ?>"><?php echo $_credit_memos[$i]['memo_inc_id']?></a>	
											<?php 
											endfor;
										else :
											echo $this->__('This RMA does not have any creditmemos');
										endif;?>
									</td>
								</tr>
								<!-- Bottom saperator line -->
								<tr>
									<td colspan=2 class="rmaDetailSap"></td>
								</tr>
								<!-- Invoices display here -->
								<tr class="paddingTr">
									<td><strong><?php echo $this->__('Invoices:');?></strong></td>
									<td><?php echo $this->getInvoices($data['invoice_number']);?></td>
								</tr>
								<!-- Bottom saperator line -->
								<tr>
									<td colspan=2 class="rmaDetailSap"></td>
								</tr>
								<!-- Outstanding amount display here -->
								<tr class="paddingTr">
									<td><strong><?php echo $this->__('Outstanding amount:');?></strong></td>
									<td><?php echo $total_amount;?></td>
								</tr>
								<!-- Bottom saperator line -->
								<tr>
									<td colspan=2 class="rmaDetailSap"></td>
								</tr>
								<!-- Return Code display here -->
								 <tr class="paddingTr">
									<td><strong><?php echo $this->__('Return Code:');?></strong></td>
									<td><?php echo Mage::helper('rma/request')->getReasonCode($data['reason_id']);?></td>
								</tr>
								<!-- Bottom saperator line -->
								<tr>
									<td colspan=2 class="rmaDetailSap"></td>
								</tr>
								<tr>
									<td colspan=2 class="clear"></td>
								</tr>
								<!-- Items edit link display here -->
								<?php if($this->getRmaStatus($data['rma_id']) == 0) :?>
									<tr>
										<td><strong><?php echo $this->__('Items');?></strong></td>
										<td><a href="<?php echo $this->getEditItemUrl($data['item_id']);?>">Edit Item</a></td>
									</tr>
								<?php endif;?>
								<!-- Order and Back buttons display here -->
								<tr>
									<td><strong>&nbsp;</strong></td>
									<td class="fr mr10">
										<span>
											<a href="<?php echo $this->getViewOrderUrl($data['order_id']);?>">
												<button class="button" type="button">
													<span><?php echo $this->__('Show Order');?></span>
												</button>
											</a>
										</span>
									</td>
									<td class="fr mr10">
										<span>
											<a href="<?php echo $this->getRmaListBackUrl();?>">
												<button class="button" type="button">
													<span><?php echo $this->__('Back');?></span>
												</button>
											</a>
										</span>
									</td>
								</tr>
								<!-- Other action heading display here -->
								<!--<tr>
									<td colspan=2><strong><?php //echo $this->__('Other actions');?></strong></td>
								</tr>
								
								<tr>
									<td colspan=2>
										<span>
											<a href="#">
												<button class="button" type="button">
													<span><?php //echo $this->__('Refund Shipping');?></span>
												</button>
											</a>
										</span>
									</td>
								</tr>-->
								<tr>
									<td colspan=2 class="clear"></td>
								</tr>
							</table>
						</fieldset>
					</div>
					<!-- Left side rma detail div end here -->
					
					<!-- Right side div for journal start here -->
					<div>
						<div class="detailRight">
							<div class="clear"></div>
							<?php $log = Mage::helper('rma/request')->getJournalLog($data['item_id']);
							foreach($log as $log): ?>
							<div>
								<div>
									 <?php echo $this->getJournalDate($log->getLog_created());?>
								</div>
								<div>
									 <?php echo $log->getLog_action();?>
								</div>
								<div class="lh0"><?php echo '...';?></div>
							</div>
							
							<div class="clear"></div>
							<?php endforeach;?>
						</div>
						<!-- Save log and customer called buttons display here -->
						<!--<div class="jornalBtnDiv">
							<div>
								<span>
									<a href="#">
										<button class="button" type="button">
											<span><?php //echo $this->__('Save log');?></span>
										</button>
									</a>
								</span>
							</div>
							<div>
								<span>
									<a href="#">
										<button class="button" type="button">
											<span><?php //echo $this->__('Customer have called');?></span>
										</button>
									</a>
								</span>
							</div>
						</div>-->
					</div>
					<!-- Right side div for journal end here -->
				</div>
			</div>
		</div>
		<?php 
		$i++;
	endforeach;
else : 
	echo Mage::helper('rma')->__('There are no RMA at this moment');
endif;?> 

<!-- Div start here for back url -->
<div class="buttons-set">
	<p class="back-link"><a href="<?php echo $this->getRmaListBackUrl() ?>"><small>&laquo; </small><?php echo $this->getBackTitle() ?></a></p>
</div>
