// <![CDATA[
	$(document).ready(function(){
		$('.comingSoon').click(function(e) {
			customAlert("Coming Soon...",e);			
		});	
			
		$('#close-customAlert').click(function(){
			$('#customAlert').trigger('close');
		});		
		$('#close-lightBox').click(function(){
			$(this).parent().trigger('close');
			if($('#loginFormContainer')){
				$('#loginFormContainer').html('');
			}
		});
		$('#close-postGalleryBox').click(function(){
			$(this).parent().trigger('close');
		});
		$('#close-reviewBox').click(function(){
			$(this).parent().trigger('close');
		});
		$('#close-postPreviewBox').click(function(){
			$(this).parent().trigger('close');
		});
		$('#close-productVideoBox').click(function(){
			$(this).parent().trigger('close');
		});
		$('#close-previewWorkBox').click(function(){
			$(this).parent().trigger('close');
		});
		$('#close-postViewGalleryBox').click(function(){
			$(this).parent().trigger('close');
		});
		$('#close-YesNoBox').click(function(){
			$(this).parent().trigger('close');
		});
		$('#close-listBox').click(function(){
			$(this).parent().trigger('close');
		});
		$('#close-stockImagesBox').click(function(){
			$(this).parent().trigger('close');
		});
		$('#close-upcomingProjectBox').click(function(){
			$(this).parent().trigger('close');
		});
		$('#close-showcasePreviewBox').click(function(){
			$(this).parent().trigger('close');
		});
		$('#close-interviewEmbedBox').click(function(){
			$(this).parent().trigger('close');
		});
		$('#close-introductoryEmbedBox').click(function(){
			$(this).parent().trigger('close');
		});
		$('#close-introductoryVideoEmbedBox').click(function(){
			$(this).parent().trigger('close');
		});
		$('#close-interviewVideoEmbedBox').click(function(){
			$(this).parent().trigger('close');
		});
	});
// ]]>							
