<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
//menu config define for showcase menu, your toadsquare, user member info header



//This config for which module and method you do not want to show member info header
$config['member_user_info'] =   array(
    'home'              =>  array(),
    'forums'            =>  array(),
    'help'              =>  array(),
    'tips'              =>  array(),
    'package'           =>  array(
        'freejoined'        => 'freejoined',
         'information'        => 'information',
        'packagestageone'   => 'packagestageone',
        'promocodejoined'       => 'promocodejoined',
        'index'             => 'index',
        'freejoined'        => 'freejoined'
    ),
    'creatives'         =>  array(),
    'associateprofessional'=>  array(),
    'enterprises'       =>  array(),
    'fans'              =>  array(),
    'filmnvideo'        =>  array(),
    'photographynart'   =>  array(),
    'musicnaudio'       =>  array(),
    'writingnpublishing'=>  array(),
    'educationnmaterial'=>  array(),
    'performancesnevents'=>  array(),
    'blogs'         =>  array(),
    'products'      =>  array(),
    'my404'         =>  array(),
    'cms'           =>  array(),
    'pressRelease'  =>  array(),
    'news'          =>  array(),
    'search'        =>  array(),
    'report_a_problem'        =>  array(),
    'showcase'        =>  array('index','developementpath','aboutme','videos','mycraves','cravingme','mypaylist'),
   
);

//-----------showing header in module --------//
//This config for which module and method you want to show  showcase info header
$config['showcase_user_info'] =   array(
    'showcase'        =>  array('index','developementpath','aboutme','videos','mycraves','cravingme','mypaylist'),
    'blogshowcase'         =>  array(),
    'buyer_comment'         =>  array(),
);


//This config for which module and method you do not want to show showcase menu
$config['showcase_menu'] =   array(
    'home'              =>  array(),
    'forums'            =>  array(),
    'help'              =>  array(),
    'tips'              =>  array(),
    'package'           =>  array(
        'freejoined'            => 'freejoined',
        'information'        => 'information',
        'packagestageone'       => 'packagestageone',
        'packagestagetwo'       => 'packagestagetwo',
        'packagestagethree'     => 'packagestagethree',
        'membershipselected'    => 'membershipselected',
        'billingdetails'        => 'billingdetails',
        'packagesummary'        => 'packagesummary',
        'index'                 => 'index',
        'freejoined'            => 'freejoined',
        'promocodejoined'       => 'promocodejoined',
        'paidjoined'            => 'paidjoined',
        'paymenterror'          => 'paymenterror',
    ),
    'creatives'         =>  array(),
    'associateprofessional'=>  array(),
    'enterprises'       =>  array(),
    'fans'              =>  array(),
    'filmnvideo'        =>  array(),
    'photographynart'   =>  array(),
    'musicnaudio'       =>  array(),
    'writingnpublishing'=>  array(),
    'educationnmaterial'=>  array(),
    'performancesnevents'=>  array(),
    'blogs'         =>  array(),
    'products'      =>  array(),
    'my404'         =>  array(),
    'cms'           =>  array(),
    'pressRelease'  =>  array(),
    'news'          =>  array(),
    'search'        =>  array(),
   
);


/*
 * --------------------------------------------------------------------------
 * Define array where you have to show gray bar spefice method or 
 * module
 * -------------------------------------------------------------------------- 
*/ 

$config['gray_bar_show']    =   array(
    'mediafrontend'         =>  array(),
    'showproject'           =>  array(),
    'showcase'              =>  array(
        'index'             =>  'index',
        'developementpath'  =>  'developementpath',
        'aboutme'           =>  'aboutme',
        'videos'            =>  'videos',
        'mycraves'          =>  'mycraves',
        'cravingme'         =>  'cravingme',
        'mypaylist'         =>  'mypaylist'
    ),
    'blogshowcase'         =>  array(),
    'buyer_comment'        =>  array(),
    'upcomingfrontend'     =>  array(),
);

/*
 * --------------------------------------------------------------------------
 * Define array where you have to show orange bar spefice method or 
 * module
 * -------------------------------------------------------------------------- 
*/ 

$config['orange_bar_show'] =   array(
    'mediafrontend'           =>  array(
        'editfilmvideocollection'        => 'editfilmvideocollection',
        'editmusicaudiocollection'        => 'editmusicaudiocollection',
        'editphotoartcollection'        => 'editphotoartcollection',
        'editwritingpubcollection'        => 'editwritingpubcollection',
        'editeducationalcollection'        => 'editeducationalcollection',
        'deletedcollection'        => 'deletedcollection',
        'musicaudiodeleted'        => 'musicaudiodeleted',
        'photoartdeleted'        => 'photoartdeleted',
        'writingpubdeleted'        => 'writingpubdeleted',
        'educationaldeleted'        => 'educationaldeleted',
    )
);


/*
 * --------------------------------------------------------------------------
 * Define module and method name will not show to fans type 
 * user while login
 * -------------------------------------------------------------------------- 
*/ 

$config['fans_privilege']  = array(
    'media'             =>  
    array( 
        'index'=>'index', 
        'getIndustryId'=>'getIndustryId', 
        'projectDescription'=>'projectDescription', 
        'mediaLastInsertDtaData'=>'mediaLastInsertDtaData', 
        'uploadMedia'=>'uploadMedia', 
        'updateProjectPrice'=>'updateProjectPrice', 
        'furtherDescription'=>'furtherDescription', 
        'additionalInformation'=>'additionalInformation', 
        'getProject'=>'getProject', 
        'writeCacheFile'=>'writeCacheFile', 
        'deletedItems'=>'deletedItems', 
        'filmNvideo'=>'filmNvideo', 
        'musicNaudio'=>'musicNaudio', 
        'writingNpublishing'=>'writingNpublishing', 
        'photographyNArt'=>'photographyNArt', 
        'filmvideo'=>'filmvideo', 
        'musicaudio'=>'musicaudio', 
        'writingpublishing'=>'writingpublishing', 
        'photographyart'=>'photographyart', 
        'educationmaterials'=>'educationmaterials', 
        'setupshowcase'=>'setupshowcase', 
        'saveMediaTools'=>'saveMediaTools', 
        'saveProjectData'=>'saveProjectData', 
        'membershipcart'=>'membershipcart', 
        'billingdetails'=>'billingdetails', 
        'membershipcartpost'=>'membershipcartpost', 
        'setcartvalues'=>'setcartvalues', 
        'addContainerMediaItem'=>'addContainerMediaItem', 
        'addCartData'=>'addCartData', 
        'billingdetailspost'=>'billingdetailspost', 
        'updatebuyerdata'=>'updatebuyerdata', 
        'purchasesummary'=>'purchasesummary', 
        'paymenterror'=>'paymenterror', 
        'paymentsuccess'=>'paymentsuccess', 
        'updatefreeaddpace'=>'updatefreeaddpace', 
        'renewcontainerexpiry'=>'renewcontainerexpiry', 
        'getAvailableMediaContainer'=>'getAvailableMediaContainer', 
        'setupsales'=>'setupsales', 
        'saveCurrency'=>'saveCurrency', 
        'setpriceformat'=>'setpriceformat', 
        'savePriceformat'=>'savePriceformat', 
        'inventorytype'=>'inventorytype', 
        'saveInventorytype'=>'saveInventorytype', 
        'setuppricing'=>'setuppricing', 
        'savePricing'=>'savePricing', 
        'setupauction'=>'setupauction', 
        'saveAuctionPrice'=>'saveAuctionPrice', 
        'pricing'=>'pricing', 
        'saveProjectPrice'=>'saveProjectPrice', 
        'inventory'=>'inventory', 
        'saveProjectInventory'=>'saveProjectInventory', 
        'previewpublish'=>'previewpublish', 
        'publicise'=>'publicise', 
        'saveProjectStatus'=>'saveProjectStatus', 
        'share'=>'share', 
        'email'=>'email', 
        'prnews'=>'prnews', 
        'prreviews'=>'prreviews', 
        'prreinterviews'=>'prreinterviews', 
        'loadMediaWizardView'=>'loadMediaWizardView', 
        'updateDataInFile'=>'updateDataInFile', 
        'saveDataInFile'=>'saveDataInFile', 
        'getDataFromFile'=>'getDataFromFile', 
        'deleteCacheFile'=>'deleteCacheFile', 
        'educationMaterial'=>'educationMaterial', 
        'suportLinksAdd'=>'suportLinksAdd', 
        'uploadMediaPopup'=>'uploadMediaPopup', 
        'moveMediaProjectInTrash'=>'moveMediaProjectInTrash', 
        'moveMediaElementInTrash'=>'moveMediaElementInTrash', 
        'shipping'=>'shipping', 
        'pickupshipping'=>'pickupshipping', 
        'saveshippingpickup'=>'saveshippingpickup', 
        'manageshippingnexturl'=>'manageshippingnexturl', 
        'uploadfile'=>'uploadfile', 
        '_projectdetailsbyid'=>'_projectdetailsbyid', 
        '_elementdetailsbyid'=>'_elementdetailsbyid', 
        '_ispriceshippingcharge'=>'_ispriceshippingcharge', 
        '_firstmainelementcreate'=>'_firstmainelementcreate', 
        '_uploadfilerequiredata'=>'_uploadfilerequiredata', 
        '_setuploadfileparams'=>'_setuploadfileparams', 
        'uploadfilepost'=>'uploadfilepost', 
        '_updateelementmedia'=>'_updateelementmedia', 
        '_indusrtydetails'=>'_indusrtydetails', 
        'uploadtitle'=>'uploadtitle', 
        'uploadtitlepost'=>'uploadtitlepost', 
        'priceshippingcharge'=>'priceshippingcharge', 
        'priceshippingchargepost'=>'priceshippingchargepost', 
        'shippingcharge'=>'shippingcharge', 
        'uploadimageinfo'=>'uploadimageinfo', 
        'setimageinformation'=>'setimageinformation', 
        'copyElementInfo'=>'copyElementInfo', 
        'uploadcreativeteam'=>'uploadcreativeteam', 
        'manageGlobalPickup'=>'manageGlobalPickup', 
        'domesticshipping'=>'domesticshipping', 
        'domesticshippingstates'=>'domesticshippingstates', 
        'getDomesticState'=>'getDomesticState', 
        'savedomesticshipping'=>'savedomesticshipping', 
        'internationalshipping'=>'internationalshipping', 
        'savezoneasglobal'=>'savezoneasglobal', 
        'manageshippingform'=>'manageshippingform', 
        'addshippingzone'=>'addshippingzone', 
        'saveshippingzone'=>'saveshippingzone', 
        'addshippingzoneprice'=>'addshippingzoneprice', 
        'saveshippingzoneprice'=>'saveshippingzoneprice', 
        'saveglobalshipping'=>'saveglobalshipping', 
        'sellerconsumptiontax'=>'sellerconsumptiontax', 
        'saveConsumptionTax'=>'saveConsumptionTax', 
        'manageConsumptionCharge'=>'manageConsumptionCharge', 
        'manageConsumptionStateTax'=>'manageConsumptionStateTax', 
        'consumptionStateTaxHtml'=>'consumptionStateTaxHtml', 
        'getConsumptionStatesList'=>'getConsumptionStatesList', 
        'euCountiesTaxPercentage'=>'euCountiesTaxPercentage', 
        'sellerpaypal'=>'sellerpaypal', 
        'sellersetting'=>'sellersetting', 
        'setprintdeliveryoptions'=>'setprintdeliveryoptions', 
        'isprojectexists'=>'isprojectexists', 
        'selectcoverimage'=>'selectcoverimage', 
        'setselectedimage'=>'setselectedimage', 
        'selecttitlendesc'=>'selecttitlendesc', 
        'settitlendescription'=>'settitlendescription', 
        'selectcollectioninfo'=>'selectcollectioninfo', 
        'setcollectioninfo'=>'setcollectioninfo', 
        'selectcreativeteam'=>'selectcreativeteam', 
        'addEditAssociative'=>'addEditAssociative', 
        'manageMemberRowHtml'=>'manageMemberRowHtml', 
        'deleteCreativeMember'=>'deleteCreativeMember', 
        'searchtoadmember'=>'searchtoadmember', 
        'searchtoadmemberresult'=>'searchtoadmemberresult', 
        'copyCreativeTeam'=>'copyCreativeTeam', 
        'selectassociatedmedia'=>'selectassociatedmedia', 
        '_usersubscriptiondetails'=>'_usersubscriptiondetails', 
        'searchassociatedmedia'=>'searchassociatedmedia', 
        'deleteSupportedMedia'=>'deleteSupportedMedia', 
        'addSupportingLink'=>'addSupportingLink', 
        'manageSupportingRowHtml'=>'manageSupportingRowHtml', 
        '_pluploadjsandcss'=>'_pluploadjsandcss', 
        'setdisplayimage'=>'setdisplayimage', 
        'uploadelementfilepost'=>'uploadelementfilepost', 
        'displayimageoption'=>'displayimageoption', 
        'setdisplayimageoption'=>'setdisplayimageoption', 
        'nextmediaoptions'=>'nextmediaoptions', 
        'movetonextstep'=>'movetonextstep', 
        'addprojectelement'=>'addprojectelement', 
        'getprojectelementcount'=>'getprojectelementcount', 
        'uploadform'=>'uploadform', 
        'setuploadformoption'=>'setuploadformoption', 
        'isprojectelementexists'=>'isprojectelementexists', 
        'publicisemediacollection'=>'publicisemediacollection', 
        'viewmediacollection'=>'viewmediacollection', 
        'editmediacollection'=>'editmediacollection', 
        'getmediacollection'=>'getmediacollection', 
        'getmediacollectionresult'=>'getmediacollectionresult', 
        'publiciseproject'=>'publiciseproject', 
        'editproject'=>'editproject', 
        'addtrailerorsamplefile'=>'addtrailerorsamplefile', 
        'setfilename'=>'setfilename', 
        'editmediaelements'=>'editmediaelements', 
        'getmediaelementresult'=>'getmediaelementresult', 
        'editprojectelement'=>'editprojectelement', 
        'deleteproject'=>'deleteproject', 
        'publishcollection'=>'publishcollection', 
        'publicisecollection'=>'publicisecollection', 
        'searchshareelements'=>'searchshareelements', 
        'searchshareelementsresult'=>'searchshareelementsresult', 
        'getelementshortlink'=>'getelementshortlink', 
        'manageelementshortlink'=>'manageelementshortlink', 
        'editwizardcollection'=>'editwizardcollection', 
        '_isaddspacerequest'=>'_isaddspacerequest', 
        'getgenreselectbox'=>'getgenreselectbox', 
        'renewmediacart'=>'renewmediacart', 
        'renewbillingdetails'=>'renewbillingdetails', 
        'renewpurchasesummary'=>'renewpurchasesummary', 
        'renewinvoiceemail'=>'renewinvoiceemail', 
        'setmediaaddtype'=>'setmediaaddtype', 
        'checkConvertion'=>'checkConvertion', 
        'renewmedialist'=>'renewmedialist', 
        'testing'=>'testing', 
        '__get'=>'__get', 
        '__call'=>'__call', 
        ),
    'upcomingprojects'  =>  array(),
    'advertising'       =>  array(),
    'collaboration'     =>  array(),
    'workprofile'       =>  array(),
    'event'             =>  array(),
    'work'              =>  array(),
    'product'           =>  array(),
    'competition'       =>  array(),
    'collaboration'     =>  array(),
);


